//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.17
//
package com.amazonaws.mobile;

import com.amazonaws.mobilehelper.config.AWSMobileHelperConfiguration;
import com.amazonaws.regions.Regions;
import com.inlocomedia.android.engagement.sample.BuildConfig;

@SuppressWarnings("ALL")
final class AWSConfiguration {
    public static final String AWS_MOBILEHUB_USER_AGENT = BuildConfig.AWS_MOBILEHUB_USER_AGENT;
    public static final Regions AMAZON_COGNITO_REGION = Regions.fromName(BuildConfig.AMAZON_COGNITO_REGION);
    public static final String AMAZON_COGNITO_IDENTITY_POOL_ID = BuildConfig.AMAZON_COGNITO_IDENTITY_POOL_ID;
    public static final String GOOGLE_CLOUD_MESSAGING_SENDER_ID = BuildConfig.GOOGLE_CLOUD_MESSAGING_SENDER_ID;
    public static final String AMAZON_SNS_PLATFORM_APPLICATION_ARN = BuildConfig.AMAZON_SNS_PLATFORM_APPLICATION_ARN;
    public static final Regions AMAZON_SNS_REGION = Regions.fromName(BuildConfig.AMAZON_SNS_REGION);
    public static final String AMAZON_SNS_DEFAULT_TOPIC_ARN = BuildConfig.AMAZON_SNS_DEFAULT_TOPIC_ARN;
    public static final String[] AMAZON_SNS_TOPIC_ARNS = {};

    private static final AWSMobileHelperConfiguration helperConfiguration = new AWSMobileHelperConfiguration.Builder()
        .withCognitoRegion(AMAZON_COGNITO_REGION)
        .withCognitoIdentityPoolId(AMAZON_COGNITO_IDENTITY_POOL_ID)
        .build();
    /**
     * @return the configuration for AWSKit.
     */
    public static AWSMobileHelperConfiguration getAWSMobileHelperConfiguration() {
        return helperConfiguration;
    }
}